security:
  oauth2:
    client:
      clientId: 228657039383-6hcv4h5pd1vs363kjjq477kqptbh7gs6.apps.googleusercontent.com
      clientSecret: A_PyrxNf5VnhgI3T8x1FwSfy
      accessTokenUri: https://www.googleapis.com/oauth2/v4/token
      userAuthorizationUri: https://accounts.google.com/o/oauth2/v2/auth
      clientAuthenticationScheme: form
      scope: openid,email,profile
    resource:
      userInfoUri: https://www.googleapis.com/oauth2/v3/userinfo
      preferTokenInfo: true
server:
  compression:
    enabled: 'true'
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: '0'
  connection-timeout: '10'
  port: 9090
spring:
  datasource:
    password: root
    tomcat:
      test-while-idle: 'true'
      validationQuery: SELECT 1
    url: jdbc:mysql://localhost:3306/giftregistry?useSSL=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: 'true'
logging:
  level:
    root: debug